// <define:__ROUTES__>
var define_ROUTES_default = {
  version: 1,
  description: "Generated by @sveltejs/adapter-cloudflare",
  include: [
    "/*"
  ],
  exclude: [
    "/_app/*",
    "/.nojekyll",
    "/apple-touch-icon.png",
    "/contributors.json",
    "/favicon.png",
    "/font/Fredoka-Regular.ttf",
    "/font/Fredoka-SemiBold.ttf",
    "/font/LilitaOne-Regular.ttf",
    "/img/icon/connect_with_strava.svg",
    "/img/icon/draw_square.svg",
    "/img/icon/layer.svg",
    "/img/icon/logo_outline.png",
    "/img/icon/powered_by_strava.svg",
    "/img/icon/print.svg",
    "/img/icon/ruler.svg",
    "/img/icon/shield.svg",
    "/img/icon/strava_logo.svg",
    "/img/icon/trash.svg",
    "/img/map/trace_end.png",
    "/img/map/trace_start.png",
    "/img/touch/homescreen144.png",
    "/img/touch/homescreen168.png",
    "/img/touch/homescreen192.png",
    "/img/touch/homescreen48.png",
    "/img/touch/homescreen72.png",
    "/img/touch/homescreen96.png",
    "/manifest.json",
    "/map_styles/basic.json",
    "/map_styles/dark.json",
    "/map_styles/datavis.json",
    "/map_styles/landscape.json",
    "/map_styles/light.json",
    "/map_styles/satellite.json",
    "/map_styles/streets.json",
    "/map_styles/topo.json",
    "/map_styles/winter.json",
    "/safari-pinned-tab.svg",
    "/",
    "/__data.json"
  ]
};

// node_modules/.pnpm/wrangler@4.95.0_@cloudflare+workers-types@4.20260529.1/node_modules/wrangler/templates/pages-dev-pipeline.ts
import worker from "/tmp/workspace/strava-tools/StravaMapper/.wrangler/tmp/pages-qqcaIH/bundledWorker-0.9136366043776998.mjs";
import { isRoutingRuleMatch } from "/tmp/workspace/strava-tools/StravaMapper/node_modules/.pnpm/wrangler@4.95.0_@cloudflare+workers-types@4.20260529.1/node_modules/wrangler/templates/pages-dev-util.ts";
export * from "/tmp/workspace/strava-tools/StravaMapper/.wrangler/tmp/pages-qqcaIH/bundledWorker-0.9136366043776998.mjs";
var routes = define_ROUTES_default;
var pages_dev_pipeline_default = {
  fetch(request, env, context) {
    const { pathname } = new URL(request.url);
    for (const exclude of routes.exclude) {
      if (isRoutingRuleMatch(pathname, exclude)) {
        return env.ASSETS.fetch(request);
      }
    }
    for (const include of routes.include) {
      if (isRoutingRuleMatch(pathname, include)) {
        const workerAsHandler = worker;
        if (workerAsHandler.fetch === void 0) {
          throw new TypeError("Entry point missing `fetch` handler");
        }
        return workerAsHandler.fetch(request, env, context);
      }
    }
    return env.ASSETS.fetch(request);
  }
};
export {
  pages_dev_pipeline_default as default
};
//# sourceMappingURL=h4ydzsweooo.js.map
